export enum Hotkey {
    Evaluate = 'evaluate',
    EvaluateTranslate = 'evaluate-translate',
    Inspect = 'inspect',
    MarketToggle = 'market-toggle',
    SettingsToggle = 'settings-toggle',
    Command1 = 'command1',
    Command2 = 'command2',
    Command3 = 'command3',
    Command4 = 'command4',
    Command5 = 'command5',
    Command6 = 'command6',
    Bookmark1 = 'bookmark1',
    Bookmark2 = 'bookmark2',
    Bookmark3 = 'bookmark3',
    Bookmark4 = 'bookmark4',
    Bookmark5 = 'bookmark5',
    Bookmark6 = 'bookmark6',
    MiscStashHighlight = 'misc-stash-highlight',
    ReplayManually = 'replay-manually'
}
